export const FEITICOS_DB = [
    { name: "Adicionar Feitiço Personalizado", description: "Cria um feitiço em branco para você editar.", custom: true },
    { name: "Prisão", description: "Toque numa criatura para aprisioná-la num espelho ou pote de vidro/pedra próximo por 1d4+1 rodadas. Alvo involuntário faz teste de Vontade (FIS) DT 7, se ele passar fica apenas atordoado por uma rodada." },
    { name: "Névoa Negra", description: "Seu corpo, roupas e equipamento se tornam uma fumaça viva que você pode controlar." },
    { name: "Manto da Noite", description: "Uma escuridão de área próxima circula um ponto de 10m de raio no campo de visão por 1d4+1 Rodadas." },
    { name: "Telecinese", description: "Nesta Rodada, mova mentalmente 1 objeto não carregado/vestido com menos de até 30 de carga. Alvo involuntário faz teste de Fortitude (FIS) DT 8, se ele passar fica apenas atordoado por uma rodada." },
    { name: "Máscara", description: "Muda sua aparência humana. Tentativas de imitar alguém caem no vale da estranheza." },
    { name: "Perpassar Reflexos", description: "Cria um portal temporário de um espelho até outro espelho já visto antes e que esteja até 15km de você (Dentro da mesma cidade/vila)." },
    { name: "Rabo de Lagarto", description: "Regenera um membro recém-amputado, que volta lentamente em 4 cenas. Esse membro fica com uma aparência distorcida e dá -2 em testes de eloquência." },
    { name: "Visão do Calor Ardente", description: "Seus olhos têm visão térmica em distância média caso esteja escuro." },
    { name: "Antropomorfizar", description: "O animal tocado ganha inteligência ou aparência humana por um dia. Animais involuntários fazem um teste de Vontade DT 7." },
    { name: "Falar com Mortos", description: "Um cadáver tocado te responde três perguntas, caso compreenda." },
    { name: "Enxerto de Alma", description: "Um objeto não vestido/usado obedece seu comando, mas é burro então tem que ser uma ordem bem clara e simples." },
    { name: "Despertar do Sono Eterno", description: "Você toca um cadáver que se levanta para servi-lo. Esse cadáver tem as estatísticas de um condenado recém criado." },
    { name: "Selo Onírico", description: "Deixa um inimigo em alcance médio suprimido por 1d4+1 rodadas. Alvo involuntário faz teste de Reflexos (MOT) DT 8, se ele passar não pode se mover só nessa rodada." },
    { name: "Letargia", description: "Uma criatura em seu campo de visão que esteja em alcance médio fica abalada por 1d6+1 rodadas. Alvo involuntário faz teste de Vontade (MENTE) DT 10." },
    { name: "Miragem do Djinn", description: "Você cria uma ilusão visual, auditiva ou olfativa. Para perceber a ilusão é necessário um teste de Vontade (MOTORAS) DT 10." },
    { name: "Aprimorar Corpo", description: "Você melhorar algum aspecto do seu corpo e recebe +2 em um atributo, só pode melhorar um atributo por vez." },
    { name: "Ouvir Sussurros", description: "Você pode ouvir sons fracos com precisão." },
    { name: "Espalhar o Medo", description: "Você emana uma presença aterradora, seres em alcance curto precisam passar num teste de Vontade (MENTE) DT 8 se não ficam amedrontados." },
    { name: "Sonda Mental", description: "Lê e influencia os pensamentos de um alvo." },
    { name: "Teia", description: "Uma espessa teia do tamanho de um bebê gruda no alvo. Ele faz reflexos com motoras DT 8, se falhar fica preso sem poder se mover nem usar os braços por 3 rodadas. Precisa passar num teste de Atletismo DT 8 para se soltar." },
    { name: "Dardo Macabro", description: "Causa 3d4 de dano sobrenatural com um dardo incorpóreo. O condenado faz um teste de ataque de Misticismo (Int, Ment ou Mot) contra o alvo que pode reagir apenas com esquiva." },
    { name: "Ventriloquismo", description: "Você fala e sua voz se projeta em um local de distância média." },
    { name: "Narcisismo", description: "Uma duplicata ilusória sua aparece sob seu controle por 1d4+1 Rodadas." },
    { name: "Graxa", description: "Uma superfície sólida de área de 3m de raio próxima torna-se extremamente escorregadia e inflamável. Reflexos (Físico) DT 8 para não escorregar e cair ao andar na área. Se acabar pegando fogo causa 4d6 de dano elemental e aplica “em chamas” em quem estiver na área." },
    { name: "Iluminar", description: "Toque um objeto para iluminá-lo como uma tocha de luz prateada. Pode mirar a luz na cara de alguém para deixar a pessoa cega dos dois olhos." },
    { name: "Remover a Podridão", description: "Purifica de água ou alimentos estragados os deixando próprio para consumo e curando um espaço de dano quando comidos, prioridade para os de menor gravidade." },
    { name: "Patas de Aranha", description: "8 patas de aranha finas, mas resistentes, surgem de suas costas. Dobra o deslocamento e pode subir pelas paredes." },
    { name: "Areia Movediça", description: "Transforma terra ou pedra firme em areia movediça por 2d4 Rodadas. Andar nessa área custa o dobro do movimento." },
    { name: "Esculpir Fogo", description: "Molda chamas, aumentando ou diminuindo em qualquer intensidade. Pode causar 3d6 de dano elemental se fizer uma labareda grande contra um inimigo em alcance curto. Reduz o dano a metade e evita condição com Reflexos DT 8." },
    { name: "Pele de Camaleão", description: "Uma criatura viva que você toca fica invisível por 3 rodadas ou até atacar alguém." },
    { name: "Saco de Plumas", description: "Por 10 rodadas um grupo de pessoas igual ao seu valor de mente fica leve como um saco de plumas e não toma dano de queda." },
    { name: "Ventos do Deserto", description: "Ventos protetores circulam uma área de 5m de diâmetro por 1d4+1 Rodadas. Enquanto você estiver nessa área você passa automaticamente em testes de esquiva." },
    { name: "Pequena Fenda", description: "Abre um espaço entre planos que pode guardar até 10 itens." },
    { name: "Mover as Areias", description: "O terreno ao seu redor se molda e move da forma que você quiser. Se tentar usar para atacar ou fazer uma arma, considere as estatísticas de uma arma especial de uma mão. Ataque com misticismo (mente ou int). Se usar para moldar o terreno, pode fazer paredes ou plataformas." },
    { name: "Olho Demoníaco", description: "Você enxerga através de um globo ocular flutuante conjurado que te obedece." },
    { name: "Transmutar Essência", description: "Você toca um alvo consentido e troca de corpo." }
];  